name: Cache and Node Dependancies
description: This Avction will allow to cahche and both Node and npm dependancies on packege-lock.json file
inputs:
 node-version:
   description: Node Js Version To use
   default: 20.x
   required: true
 working-dir: 
   description: The Directory of the Application
   defaults:
   required: false
 target-env:
    description: '"dev" or "prod". Controls whether dev dependencies are installed'
    default: dev
    required: false



runs:
  using: composite
  steps:
   - name: Setup NodeJs Version ${{ inputs.node-version }}}
     uses: actions/setup-node@v3
     with:
       node-version: ${{ inputs.node-version }}

   - name: Cache dependancies
     id: cache
     uses: actions/cache@v4
     with:
      path: ${{ inputs.working-dir }}/node_modules
      key: node-module-${{ hashfiles( format('{0}/{1}',inputs.working-dir,'package-lock.json' )) }}
   
   - name: Install Dependancies
     if: steps.cache.outputs.cache-hit != 'true' 
     run: ${{ inputs.target-env== 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
     shell: bash
     working-directory: ${{inputs.working-dir}}

   - name: Install Dependancies
     if: steps.cache.outputs.cache-hit != 'true' && inputs.target-env== 'dev'
     run: npm ci --omit=dev
     shell: bash
     working-directory: ${{inputs.working-dir}}


        



