name: 04-using-actions

on: workflow_dispatch
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/my-react-app 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Listing folder directory
        run: ls

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node_version: '18.x'  

      - name: download cached dependancies
        
         
         

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Test
        run: npm run test
