name: 04-using-actions

on: push
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults :
         run :
         working-directory: 04-using-actions/my-react-app 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Listing folder directory
        run: ls

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node_version: '12.x'  # Corrected node version to a valid one

      - name: Install Dependencies
        run: npm ci
        
      
      - name : Run Unit Test
        run: npm run test
     



