name : 04-using-actions

on : push
jobs:
  build:
    runs-on : ubuntu-latest
    steps :
     - name : Checkout code
       uses : actions/checkout@v4
     - name : listing folder directory
       run  : ls
     - name : Setup node
       uses : actions/setup-node@v3
       with :
         node_version : '20.x'
     -name  : Install Dependancies
      run   : ci
      working-directory: 04-using-actions



