name : 09-using functions

on :
 pull_request:
 workflow_dispatch:

jobs:
  echo1:
   runs-on : ubuntu-latest

   steps:
    - name : Print PR title
      run: echo "${{github.event.pull_request.title}}"
    - name : Print PR titles
      run : |
        cat << EOF 
        ${{ toJSON(github.event.pull_request.labels) }}
        EOF
    - name: Bug Fix
      if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
      run: echo "I am bug fix"
    - name : Sleep WF
      run :  sleep 20

    - name: Failing step
      run: exit 1 
    - name : I will be Skipped
      if: ${{ success() }}
      run: echo "I will print if Previous step is executed."
    - name : I will execute
      if: ${{ failure() }}
      run: echo "I willprint if the previous step is failed"
    
    - name : I will execute 
      if: ${{!cancelled ()}}
      run : echo "I will Always print unless work flow is cancelled"

    - name : I will execute when cancelled workflow
      if: ${{cancelled() }}   
      run : I will always  print ,when the workflow is cancelled
