name: 16-working with environ ments

on:
 workflow_dispatch: 
   inputs:
    target-env:
      type: environment
      default: staging

jobs:
   echo:
       runs-on: ubuntu-latest
       environment: ${{inputs.target-env}}
       env: 
          my-env-value: ${{vars.MY_ENV_VALUE || 'default value '}}

       steps: 
          - name: Echo vars
            run: 
             echo " Env Variable:${{vars.MY_ENV_VALUE}}"
     
