name: 17-2-custom Actions-JS
run-name: 17-2-custom Actions-JS | BB ${inputs.base-branch}}  - TB  ${{inputs.target-branch}} - WD  ${{inputs.working-dir}}

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: master
      target-branch:
        type: string
        default: update-dependencies
      working-dir:
        type: string
        default: 17-custom-actions/react-app

jobs:
  dependancy-update:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependancy Updates
        uses: ./.github/actions/js-dependency-update
        with:
           base-branch: ${{inputs.base-branch}}
           target-branch: ${{inputs.target-branch}}
           working-directory: ${{inputs.working-dir}}
        
